package feelsafeHibernatePackage;



/**
 * AbstractRooms generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRooms  implements java.io.Serializable {


    // Fields    

     private String roomid;
     private Employees employees;
     private Patient patient;
     private Integer roomtype;


    // Constructors

    /** default constructor */
    public AbstractRooms() {
    }

	/** minimal constructor */
    public AbstractRooms(String roomid) {
        this.roomid = roomid;
    }
    
    /** full constructor */
    public AbstractRooms(String roomid, Employees employees, Patient patient, Integer roomtype) {
        this.roomid = roomid;
        this.employees = employees;
        this.patient = patient;
        this.roomtype = roomtype;
    }

   
    // Property accessors

    public String getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Integer getRoomtype() {
        return this.roomtype;
    }
    
    public void setRoomtype(Integer roomtype) {
        this.roomtype = roomtype;
    }
   








}