package feelsafeHibernatePackage;



/**
 * AbstractAppointments generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAppointments  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Employees employeesByEmployeeuserid;
     private Employees employeesByDoctoruserid;
     private String patientname;
     private Integer age;
     private Integer sex;
     private String healthproblem;
     private String appointmentdate;
     private String appointmenttime;
     private Integer type;


    // Constructors

    /** default constructor */
    public AbstractAppointments() {
    }

	/** minimal constructor */
    public AbstractAppointments(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractAppointments(Integer id, Employees employeesByEmployeeuserid, Employees employeesByDoctoruserid, String patientname, Integer age, Integer sex, String healthproblem, String appointmentdate, String appointmenttime, Integer type) {
        this.id = id;
        this.employeesByEmployeeuserid = employeesByEmployeeuserid;
        this.employeesByDoctoruserid = employeesByDoctoruserid;
        this.patientname = patientname;
        this.age = age;
        this.sex = sex;
        this.healthproblem = healthproblem;
        this.appointmentdate = appointmentdate;
        this.appointmenttime = appointmenttime;
        this.type = type;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Employees getEmployeesByEmployeeuserid() {
        return this.employeesByEmployeeuserid;
    }
    
    public void setEmployeesByEmployeeuserid(Employees employeesByEmployeeuserid) {
        this.employeesByEmployeeuserid = employeesByEmployeeuserid;
    }

    public Employees getEmployeesByDoctoruserid() {
        return this.employeesByDoctoruserid;
    }
    
    public void setEmployeesByDoctoruserid(Employees employeesByDoctoruserid) {
        this.employeesByDoctoruserid = employeesByDoctoruserid;
    }

    public String getPatientname() {
        return this.patientname;
    }
    
    public void setPatientname(String patientname) {
        this.patientname = patientname;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getHealthproblem() {
        return this.healthproblem;
    }
    
    public void setHealthproblem(String healthproblem) {
        this.healthproblem = healthproblem;
    }

    public String getAppointmentdate() {
        return this.appointmentdate;
    }
    
    public void setAppointmentdate(String appointmentdate) {
        this.appointmentdate = appointmentdate;
    }

    public String getAppointmenttime() {
        return this.appointmenttime;
    }
    
    public void setAppointmenttime(String appointmenttime) {
        this.appointmenttime = appointmenttime;
    }

    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
   








}