package feelsafeHibernatePackage;



/**
 * AbstractHealth generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractHealth  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Employees employees;
     private String symptoms;
     private String diseasesname;
     private String medication;


    // Constructors

    /** default constructor */
    public AbstractHealth() {
    }

	/** minimal constructor */
    public AbstractHealth(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractHealth(Integer id, Employees employees, String symptoms, String diseasesname, String medication) {
        this.id = id;
        this.employees = employees;
        this.symptoms = symptoms;
        this.diseasesname = diseasesname;
        this.medication = medication;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }

    public String getDiseasesname() {
        return this.diseasesname;
    }
    
    public void setDiseasesname(String diseasesname) {
        this.diseasesname = diseasesname;
    }

    public String getMedication() {
        return this.medication;
    }
    
    public void setMedication(String medication) {
        this.medication = medication;
    }
   








}