package feelsafeHibernatePackage;



/**
 * AbstractOtherfees generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractOtherfees  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Employees employees;
     private String equipmentname;
     private Float fees;


    // Constructors

    /** default constructor */
    public AbstractOtherfees() {
    }

	/** minimal constructor */
    public AbstractOtherfees(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractOtherfees(Integer id, Employees employees, String equipmentname, Float fees) {
        this.id = id;
        this.employees = employees;
        this.equipmentname = equipmentname;
        this.fees = fees;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public String getEquipmentname() {
        return this.equipmentname;
    }
    
    public void setEquipmentname(String equipmentname) {
        this.equipmentname = equipmentname;
    }

    public Float getFees() {
        return this.fees;
    }
    
    public void setFees(Float fees) {
        this.fees = fees;
    }
   








}