package feelsafeHibernatePackage;



/**
 * AbstractDoctorfees generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDoctorfees  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Employees employees;
     private String healthproblem;
     private Float fees;


    // Constructors

    /** default constructor */
    public AbstractDoctorfees() {
    }

	/** minimal constructor */
    public AbstractDoctorfees(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractDoctorfees(Integer id, Employees employees, String healthproblem, Float fees) {
        this.id = id;
        this.employees = employees;
        this.healthproblem = healthproblem;
        this.fees = fees;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public String getHealthproblem() {
        return this.healthproblem;
    }
    
    public void setHealthproblem(String healthproblem) {
        this.healthproblem = healthproblem;
    }

    public Float getFees() {
        return this.fees;
    }
    
    public void setFees(Float fees) {
        this.fees = fees;
    }
   








}