package feelsafeHibernatePackage;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractPatient generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPatient  implements java.io.Serializable {


    // Fields    

     private String patientuserid;
     private Employees employeesByEmployeeuserid;
     private Employees employeesByDoctorconsultedid;
     private String password;
     private String name;
     private Integer age;
     private Integer sex;
     private String bloodgroup;
     private Integer testundergone;
     private Integer ecg;
     private Integer bloodtest;
     private Integer xray;
     private Integer scan;
     private String address;
     private String mobilenumber;
     private String healthproblem;
     private String dietspecified;
     private String prescribedmedicines;
     private Set roomses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractPatient() {
    }

	/** minimal constructor */
    public AbstractPatient(String patientuserid) {
        this.patientuserid = patientuserid;
    }
    
    /** full constructor */
    public AbstractPatient(String patientuserid, Employees employeesByEmployeeuserid, Employees employeesByDoctorconsultedid, String password, String name, Integer age, Integer sex, String bloodgroup, Integer testundergone, Integer ecg, Integer bloodtest, Integer xray, Integer scan, String address, String mobilenumber, String healthproblem, String dietspecified, String prescribedmedicines, Set roomses) {
        this.patientuserid = patientuserid;
        this.employeesByEmployeeuserid = employeesByEmployeeuserid;
        this.employeesByDoctorconsultedid = employeesByDoctorconsultedid;
        this.password = password;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.bloodgroup = bloodgroup;
        this.testundergone = testundergone;
        this.ecg = ecg;
        this.bloodtest = bloodtest;
        this.xray = xray;
        this.scan = scan;
        this.address = address;
        this.mobilenumber = mobilenumber;
        this.healthproblem = healthproblem;
        this.dietspecified = dietspecified;
        this.prescribedmedicines = prescribedmedicines;
        this.roomses = roomses;
    }

   
    // Property accessors

    public String getPatientuserid() {
        return this.patientuserid;
    }
    
    public void setPatientuserid(String patientuserid) {
        this.patientuserid = patientuserid;
    }

    public Employees getEmployeesByEmployeeuserid() {
        return this.employeesByEmployeeuserid;
    }
    
    public void setEmployeesByEmployeeuserid(Employees employeesByEmployeeuserid) {
        this.employeesByEmployeeuserid = employeesByEmployeeuserid;
    }

    public Employees getEmployeesByDoctorconsultedid() {
        return this.employeesByDoctorconsultedid;
    }
    
    public void setEmployeesByDoctorconsultedid(Employees employeesByDoctorconsultedid) {
        this.employeesByDoctorconsultedid = employeesByDoctorconsultedid;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getBloodgroup() {
        return this.bloodgroup;
    }
    
    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }

    public Integer getTestundergone() {
        return this.testundergone;
    }
    
    public void setTestundergone(Integer testundergone) {
        this.testundergone = testundergone;
    }

    public Integer getEcg() {
        return this.ecg;
    }
    
    public void setEcg(Integer ecg) {
        this.ecg = ecg;
    }

    public Integer getBloodtest() {
        return this.bloodtest;
    }
    
    public void setBloodtest(Integer bloodtest) {
        this.bloodtest = bloodtest;
    }

    public Integer getXray() {
        return this.xray;
    }
    
    public void setXray(Integer xray) {
        this.xray = xray;
    }

    public Integer getScan() {
        return this.scan;
    }
    
    public void setScan(Integer scan) {
        this.scan = scan;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobilenumber() {
        return this.mobilenumber;
    }
    
    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }

    public String getHealthproblem() {
        return this.healthproblem;
    }
    
    public void setHealthproblem(String healthproblem) {
        this.healthproblem = healthproblem;
    }

    public String getDietspecified() {
        return this.dietspecified;
    }
    
    public void setDietspecified(String dietspecified) {
        this.dietspecified = dietspecified;
    }

    public String getPrescribedmedicines() {
        return this.prescribedmedicines;
    }
    
    public void setPrescribedmedicines(String prescribedmedicines) {
        this.prescribedmedicines = prescribedmedicines;
    }

    public Set getRoomses() {
        return this.roomses;
    }
    
    public void setRoomses(Set roomses) {
        this.roomses = roomses;
    }
   








}