package feelsafeHibernatePackage;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Employees generated by MyEclipse - Hibernate Tools
 */
public class Employees extends AbstractEmployees implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Employees() {
    }

	/** minimal constructor */
    public Employees(String username) {
        super(username);        
    }
    
    /** full constructor */
    public Employees(String username, String password, String firstname, String lastname, String address, String phone, Integer sex, String nationality, String verificationcode, Integer type, String consultinghours, String qualification, String specialist, Set otherfeeses, Set appointmentsesForEmployeeuserid, Set healths, Set roomses, Set patientsForEmployeeuserid, Set doctorfeeses, Set patientsForDoctorconsultedid, Set appointmentsesForDoctoruserid) {
        super(username, password, firstname, lastname, address, phone, sex, nationality, verificationcode, type, consultinghours, qualification, specialist, otherfeeses, appointmentsesForEmployeeuserid, healths, roomses, patientsForEmployeeuserid, doctorfeeses, patientsForDoctorconsultedid, appointmentsesForDoctoruserid);        
    }
   
}
