package feelsafeHibernatePackage;
// Generated by MyEclipse - Hibernate Tools



/**
 * Health generated by MyEclipse - Hibernate Tools
 */
public class Health extends AbstractHealth implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Health() {
    }

	/** minimal constructor */
    public Health(Integer id) {
        super(id);        
    }
    
    /** full constructor */
    public Health(Integer id, Employees employees, String symptoms, String diseasesname, String medication) {
        super(id, employees, symptoms, diseasesname, medication);        
    }
   
}
