package feelsafeHibernatePackage;
// Generated by MyEclipse - Hibernate Tools



/**
 * Otherfees generated by MyEclipse - Hibernate Tools
 */
public class Otherfees extends AbstractOtherfees implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Otherfees() {
    }

	/** minimal constructor */
    public Otherfees(Integer id) {
        super(id);        
    }
    
    /** full constructor */
    public Otherfees(Integer id, Employees employees, String equipmentname, Float fees) {
        super(id, employees, equipmentname, fees);        
    }
   
}
