package feelsafeHibernatePackage;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Patient generated by MyEclipse - Hibernate Tools
 */
public class Patient extends AbstractPatient implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Patient() {
    }

	/** minimal constructor */
    public Patient(String patientuserid) {
        super(patientuserid);        
    }
    
    /** full constructor */
    public Patient(String patientuserid, Employees employeesByEmployeeuserid, Employees employeesByDoctorconsultedid, String password, String name, Integer age, Integer sex, String bloodgroup, Integer testundergone, Integer ecg, Integer bloodtest, Integer xray, Integer scan, String address, String mobilenumber, String healthproblem, String dietspecified, String prescribedmedicines, Set roomses) {
        super(patientuserid, employeesByEmployeeuserid, employeesByDoctorconsultedid, password, name, age, sex, bloodgroup, testundergone, ecg, bloodtest, xray, scan, address, mobilenumber, healthproblem, dietspecified, prescribedmedicines, roomses);        
    }
   
}
