package feelsafeHibernatePackage;
// Generated by MyEclipse - Hibernate Tools



/**
 * Rooms generated by MyEclipse - Hibernate Tools
 */
public class Rooms extends AbstractRooms implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Rooms() {
    }

	/** minimal constructor */
    public Rooms(String roomid) {
        super(roomid);        
    }
    
    /** full constructor */
    public Rooms(String roomid, Employees employees, Patient patient, Integer roomtype) {
        super(roomid, employees, patient, roomtype);        
    }
   
}
